# Generated by Django 5.0.6 on 2024-07-23 12:55

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=1, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1000, 800], upload_to='products/images/'),
            preserve_default=False,
        ),
    ]
